window.INDUSTRY7VIEW_CARDS = {
  project: '创新药第一条',
  brand: 'INDUSTRY 7VIEW',
  sourceUrl: 'industry7view.com/research/innovative-drug/',
  cover: {
    id: '00-cover-card',
    type: 'cover',
    tag: '创新药',
    kicker: 'INDUSTRY 7VIEW / 医药',
    titleHtml: '创新药<br /><span class="gold">真的变天了</span>',
    subtitle: '中国创新药，开始被全球买单',
    badge: '第一条',
    footer: 'industry7view.com / innovative-drug',
  },
  extras: [
    {
      id: '08-evidence-grid-card',
      type: 'evidenceGrid',
      tag: '证据墙',
      meta: 'EVIDENCE / 案例验证',
      titleHtml: '谁在为<br /><span class="gold">中国创新药</span>买单？',
      subtitle: '不是情绪升温，而是全球药企真实交易。',
      evidences: [
        { label: 'MNC 药企', value: 'License-out' },
        { label: 'BD 交易', value: '首付款' },
        { label: '临床资产', value: '差异化数据' },
        { label: '海外权益', value: '全球定价' },
      ],
      footer: '证据墙负责展示“谁在买、买什么、怎么兑现”。',
    },
  ],
  cards: [
    {
      id: '01-hook-card',
      type: 'hook',
      tag: '创新药',
      meta: 'THESIS / 认知纠偏',
      titleHtml: '创新药 <span class="gold">≠</span><br /><span class="risk">医药行情</span>',
      subtitle: '真正变化是全球药企开始买单。',
      footer: '短视频讲判断，长文讲完整逻辑。',
    },
    {
      id: '02-data-hero-card',
      type: 'dataHero',
      tag: '数据冲击',
      meta: 'DATA / 证据锚点',
      number: '1356.55',
      unit: '亿美元',
      label: '2025年中国创新药BD出海交易总金额',
      compareText: '2024年为519亿美元',
      insight: '一年时间，交易金额翻了两倍多。',
      footer: '大数字不是结论，是验证线索。',
    },
    {
      id: '03-logistics-card',
      type: 'logistics',
      tag: '产业类比',
      meta: 'ANALOGY / 讲成人话',
      titleHtml: '创新药 =<br /><span class="gold">新钥匙</span>',
      subtitle: '不是复制旧药，而是重新开锁。',
      footer: '仿制药配钥匙，创新药造钥匙。',
    },
    {
      id: '04-not-a-is-b',
      type: 'compare',
      tag: '真实逻辑',
      oldText: '总金额',
      newText: '首付款',
      explain: '总金额不等于真实兑现。',
      footer: 'BD故事不等于现金流落地。',
    },
    {
      id: '05-business-loop',
      type: 'loop',
      tag: '价值路径',
      title: '创新药从实验室到资产重估要过五关',
      steps: ['靶点发现', '临床验证', 'BD出海', '支付准入', '销售放量'],
      footer: '判断产业，不只看故事，要看兑现。',
    },
    {
      id: '06-tracking-checklist',
      type: 'checklist',
      tag: '跟踪清单',
      titleHtml: '创新药<br />看三个变量',
      items: [
        { title: '首付款', desc: '看对方真实认可度。' },
        { title: '临床数据', desc: '看疗效安全性差异。' },
        { title: '支付落地', desc: '看医保商保能否承接。' },
      ],
      footer: '适合收藏：首付、数据、支付。',
    },
    {
      id: '07-closing-quote',
      type: 'quote',
      tag: '一句话结论',
      meta: 'FINAL TAKEAWAY',
      titleHtml: '不是行情重来，<br />是<span class="gold">资产重估</span>',
      subtitle: '核心是数据、首付和放量。',
      url: 'industry7view.com/research/innovative-drug/',
      footer: '本文仅作产业研究和知识整理，不构成投资建议。',
    },
  ],
};
